### ISSUE TITLE
Origin version compatibility

### ISSUE THREAD

**Issue by adolfintel** [adolfintel/ME2KasumiCrashFix#1]
Apparently the DRM on the Origin version is interfering with the fix, as mentioned [here](https://github.com/CookiePLMonster/SilentPatchME/issues/1).

**Comment by mirh** [comment]
https://github.com/Erik-JS/masseffect-binkw32/issues/10
https://github.com/Erik-JS/masseffect-binkw32/commit/1393e15c38f484ebe3f6ce383c223a6c430719aa
Can this give you any clue?

**Comment by adolfintel** [comment]
I tried implementing the same workaround, can you see if it works?

[ME2KasumiCrashFix.asi.zip](https://github.com/adolfintel/ME2KasumiCrashFix/files/5552224/ME2KasumiCrashFix.asi.zip)

**Comment by mirh** [comment]
Mhh nope

**Comment by adolfintel** [comment]
So the pattern must be different, I'll need a memory dump.
Send it to info@fdossena.com if you have anything sensitive running

**Comment by Mgamerz** [comment]
Here's the dumps. I made an asi that would stall game as soon as it attached so it should minimize the amount of other stuff that loaded into the process. There is minidump and full dump.

Edit: I'm sending it to you as an email cause apparently dump has loads of extra data in it.

The ASI only has this code so it should not be misleading:

```
BOOL WINAPI DllMain(HMODULE hModule, DWORD dwReason, LPVOID lpReserved)
{
	switch (dwReason)
	{
	case DLL_PROCESS_ATTACH:
		MessageBox(NULL,L"Take snapshot now.",L"Stall ASI", MB_ICONINFORMATION);

```

**Comment by adolfintel** [comment]
Downloaded, you can delete the dump now.
I'll keep you posted.

**Comment by Mgamerz** [comment]
I know with the original binkw32 loader we had, we had to wait for the binary to fully setup due to origin decrypting in memory. Sometimes it took like 1-2s of retrying to find the pattern. Might be the issue here?

**Comment by adolfintel** [comment]
@Mgamerz Can you test this version? I changed the whole search and patch mechanism

[ME2KasumiCrashFix.asi.zip](https://github.com/adolfintel/ME2KasumiCrashFix/files/5555510/ME2KasumiCrashFix.asi.zip)

**Comment by Mgamerz** [comment]
Didn't throw an error this time.

**Comment by adolfintel** [comment]
Awesome :)
Can you load saves?

**Comment by Mgamerz** [comment]
Tested, it loads on origin ME2Game and MassEffect2. I can load saves.

**Comment by adolfintel** [comment]
Great. I'll upload the source code and new binaries soon and update the article tomorrow.

**Comment by adolfintel** [comment]
Done!

**Comment by mirh** [comment]
Just for the records
Of all the fixes people had been floating around in the past (`-nomoviestartup`, switching to windowed mode, repairing game files and the usual evergreen random compatibility modes) was any even good?

**Comment by adolfintel** [comment]
-nomoviesstartup worked, but I'd hardly call it a fix because you can't play the rest of the game with that, it skips all the bink videos. I wanted something that would fix it once and for all.

**Comment by Mgamerz** [comment]
The picture in the article probably should be updated so it matches the text for the directions. It's still the same as the one without /asi.

**Comment by adolfintel** [comment]
I know, I'll update the article tomorrow.

**Comment by mirh** [comment]
https://www.pcgamingwiki.com/wiki/Mass_Effect_2#Game_freeze_on_Illium
Why have people to write such... allegedly working but ideally impossible stuff?

**Comment by adolfintel** [comment]
The freeze on Illium is not caused by the same bug as the kasumi crash. I can confirm that it can be easily "fixed" by playing in borderless fullscreen. Not sure why they recommend lowering graphical settings and resolution, PCGW is full of bullshit like that, it's like the pseudoscience of game fixes

**Comment by mirh** [comment]
If your working theory is that it could be a file that doesn't exist, it should be pretty easy to check with procmon anyway.

**Comment by adolfintel** [comment]
No, that was a theory for the kasumi crash. The illium freeze is probably an engine bug, maybe in the streaming code. I have no idea how to debug it, I tried attaching a debugger to it but it jumps around way too much for me to understand what's happening, all I can tell is that the main thread is stuck in an infinite loop.

**Comment by mirh** [comment]
I still meant for kasumi, I didn't understand illium was yet another thing

**Comment by Mgamerz** [comment]
I'm curious if in your article you could go into a bit more depth about how you know what that code is in Psuedo C. Did you use Ghidra? The IDA decompiler? Do you just know what it is by looking at it from experience?

**Comment by adolfintel** [comment]
No, I just looked at the code. I'm kinda new to the whole disassembly thing, but it should be correct. I'm genuinely surprised that I was able to make this fix.

**Comment by adolfintel** [comment]
@mirh did you edit PCGW? https://www.pcgamingwiki.com/wiki/Mass_Effect_2#Crash_during_vehicle_chase_on_Illium

If so, did you test that this fix actually helps with that problem?

**Comment by mirh** [comment]
No I didn't test it. 
~~But that's the problem we are talking about isn't it?~~
...
Don't tell me, the "end of the vehicle chase" isn't the the end of kasumi's loyalty mission.. is it?

**Comment by adolfintel** [comment]
The vehicle chase is in the lair of the shadow broker. That DLC crashes occasionally, but nothing that a good restart won't solve

**Comment by mirh** [comment]
Fixed it, sorry.

**Comment by adolfintel** [comment]
@Mgamerz I made another little tweak: an ASI that imports saves from ME1 without having to use the configuration utility. It was another pet peeve of mine.

I'm sorry to bother you again, but could you test it on the origin version? I'll upload the source code if it works.

[ME2AutoImport.asi.zip](https://github.com/adolfintel/ME2KasumiCrashFix/files/5565679/ME2AutoImport.asi.zip)

**Comment by mirh** [comment]
Well, the game loads at least. 
But I'm wondering.. Was it really needed? Like, I get MassEffect2Config isn't the sharpest tool on the shed, but wouldn't something like this be even quicker in a worst case scenario?

    copy "%USERPROFILE%\My Documents\Bioware\Mass Effect\Save\Char_*.MassEffectSave" "%USERPROFILE%\My Documents\Bioware\Mass Effect 2\Save\ME1\"

**Comment by adolfintel** [comment]
Yeah that's what I used to do: I made a launcher a few years ago that copies them. Now that I've learned to make ASI mods I wanted to get rid of it.

It doesn't modify the game code, it literally just creates the folders if needed and copies the saves if they exist, so it should be compatible with all versions of ME2.

**Comment by mirh** [comment]
I see (though, to be pedantic, erik's dll doesn't work with 1.0 :stuck_out_tongue:)
I guess this would add some kind of seamlessness whenever you jump from ME1 to ME2 ([custom](https://answers.ea.com/t5/Mass-Effect-1/Saving-in-wrong-location/td-p/458748) save paths aside)

**Comment by Mgamerz** [comment]
Does the config utility copy saves if they aren't marked as completed?

**Comment by adolfintel** [comment]
Nope, only completed saves. ME1 generates a file called Char_something.MassEffectSave when you finish the game

**Comment by adolfintel** [comment]
Just a quick update on this. I'm almost at the end of the run without a single crash. It's possible that this fix also gets rid of the occasional crashes, like the one when you meet Vasir, the one on the shadow broker ship, the one during the arrival DLC, etc.

**Comment by Mgamerz** [comment]
Nice. Was just about to ask how your testing was going. Just redid a bunch of stuff related to ASI mods in my code and was hoping to add yours to the DB.

**Comment by adolfintel** [comment]
Please do, I hope it helps the community.

Btw, I had a chance to try your ME3TweaksModManager, I'll send you an email with a couple of problems I found :)

**Comment by mirh** [comment]
How frequent are those issues normally?
Because I mean, I beat the game without any DLC back in the days and I don't recall crashes of sort. 

If they aren't rare, I guess like your playthrough could quite substantiate the other crashes being correlated... otherwise I guess it's not that much statistically significant.

**Comment by adolfintel** [comment]
In my experience, the Vasir crash happens about 1 in 3 times, same for the shadow broker ship, the crash during Arrival is more rare, maybe 1 in 10 times.

Obviously, I could have been lucky, I would test them further but they only happen when the game has been running for a while.

**Comment by adolfintel** [comment]
I just replaced Erik's pattern finding code with my own simpler version. Doesn't really change anything, but using his code was total overkill.

**Comment by Mgamerz** [comment]
When you're happy with asi, can you make it a github release (as the direct .asi file). The way my ASI Manager works (which is used by all the modding tools) is that the downloaded file is hash checked against the known value, to ensure that the asi is not swapped out with something nefarious. This is also how I check versioning to ensure two duplicate ASIs are not installed at the same time. See the releases here to see how we do it for github releases:

https://github.com/ME3Tweaks/ME3-ASI-Plugins/releases

**Comment by adolfintel** [comment]
Did I do it right? https://github.com/adolfintel/ME2KasumiCrashFix/releases

**Comment by Mgamerz** [comment]
Added to the ASI DB. Users will be able to install it from ASI Mod Manager within ME3Tweaks Mod Manager within the next day.

![image](https://user-images.githubusercontent.com/2738836/100298648-e58b5380-2f4e-11eb-8d26-46d089d5df1a.png)

**Comment by mirh** [comment]
As I think I hinted above, I feel like this \*completely indisputable\* fix should be pushed a bit more vehemently than usual to users (akin to physx issues or LAA for example)

**Comment by adolfintel** [comment]
Nice :) If you could put my name (Federico Dossena) instead of my cringy github username that would be great :laughing: 

@mirh Can you fill me in on this physx thing? I've always renamed MassEffect.exe to ut3.exe to get rid of the admin request, installed physx legacy and then installed regular physx and it always worked.

**Comment by mirh** [comment]
Yes, it's that one. You are already quite informed. 
You don't need any renaming though, just tag the executable with the RUNASINVOKER flag in the registry.
